title: 被遗忘的世界线
author: fooage
email: nullptr.wang@gmail.com
description: > # This ">" is ignore newlines until the next things.
  This is my personal blog, which records useful and fun things in my life. If it helps you then just star！
show_excerpts: true # Set to show the excerpts on the homepage.
sass:
  # This is the style sheet file path that applied to the blog.
  sass_dir: _sass

plainwhite:
  name: fooage
  tagline: 1.048596
  # Minima date format, refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this.
  date_format: '%b %-d, %Y'
  # Build a sitemap for search engine crawling.
  sitemap: true
  search: true
  dark_mode: false
  # Path from the base directory of avatar.
  portfolio_image: 'assets/portfolio.png'
  html_lang: 'zh-CN'
  # Adaptive phone small screen.
  condensed_mobile:
    - page
    - post
  social_links:
    github: fooage
    # If you want more social network links, you need to add them here and add sentences in the file to build it.

# This topic is very brief and bright, and I am very grateful to the author samarsault for his silent contribution.
remote_theme: plainwhite

plugins:
  - jekyll-seo-tag
